version: '3'
services:
#  searchcode:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - manticore
#      - mysql
  manticore:
    build:
      context: .
      dockerfile: ./manticore.Dockerfile
    ports:
      - "9306:9306"
  mysql:
    build:
      context: .
      dockerfile: ./mysql.Dockerfile
    ports:
      - "3306:3306"
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: searchcode
      # MYSQL_ROOT_PASSWORD: example
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"